package algorithm;

import java.util.EnumSet;
import java.util.Set;

public enum MajorType {
	ACCOUNTING(),
	ACTUARIAL_SCIENCE(),
	AERONAUTICAL_ASTRONAUTICAL_ENGINEERING(),
	AGRIBUSINESS_APPLIED(),
	AGRICULTURAL_ENVIRONMENTAL_DEVELOPMENTAL(),
	ANTHROPOLOGY(),
	ARABIC(),
	BIOLOGY(),
	BUSINESS(),
	BUSINESS_ADMINISTRATION(),
	CHEMISTRY(),
	CHINESE(),
	CIVIL_ENGINEERING(),
	COMMUNICATION(),
	COMPUTER_INFORMATION_SCIENCE(),
	COMPUTER_SCIENCE_ENGINEERING(),
	CONSTITUTIONAL_LAW(),
	CONSUMER_FAMILY_FINANCIAL_SERVICES(),
	DATA_ANALYTICS(),
	ECONOMICS(),
	ECONOMICS_BUSINESS(),
	ELECTRICAL_COMPUTER_ENGINEERING(),
	ENGINEERING(),
	ENGINEERING_PHYSICS(),
	ENGINEERING_SCIENCES(),
	ENGLISH(),
	ENTREPRENEURSHIP(),
	ENVIRONMENT_ECONOMY_DEVELOPMENT_SUSTAINABILITY(),
	FINANCE(),
	FINANCIAL_MATHEMATICS(),
	FRENCH(),
	GENDER_STUDIES(),
	GEOGRAPHICAL_INFORMATION_SCIENCE(),
	GEOMATICS_ENGINEERING(),
	GERMAN(),
	HEALTH_INFORMATION_MANAGEMENT_SYSTEMS(),
	HISTORY(),
	INDUSTRIAL_SYSTEMS_ENGINEERING(),
	INFORMATION_SYSTEMS(),
	INTERNATIONAL_STUDIES(),
	LANDSCAPE_DESIGN_MANAGEMENT(),
	LEADERSHIP_STUDIES(),
	LINGUISTICS(),
	MATHEMATICAL_SCIENCES(),
	MATHEMATICS(),
	MECHANICAL_ENGINEERING(),
	ORGANIZATIONAL_COMMUNICATION(),
	PHILOSOPHY(),
	PHYSICS(),
	POLITICAL_SCIENCE(),
	PUBLIC_HEALTH(),
	PSYCHOLOGY(),
	SOCIOLOGY(),
	SOMALI(),
	SPANISH(),
	SPANISH_FOR_BUSINESS(),
	STATISTICS(),
	STRATEGIC_COMMUNICATION(),
	THEATRE();

	private Set<MajorType> related;
	static {
		for (MajorType t : MajorType.values()) {
			t.related = EnumSet.noneOf(MajorType.class);
		}
	}

	private MajorType(MajorType... related) {
		for (MajorType type : related) {
			this.related.add(type);
		}
	}
	// Need way to categorize "hard science"
}

