package algorithm;

public enum Weight {
	WEAKLY_DISCOURAGED,
	DISCOURAGED,
	STRONGLY_DISCOURAGED,
	NOT_REQUIRED,
	NOT_REQUIRED_WEAKLY_PREFERRED,
	NOT_REQUIRED_PREFERRED,
	NOT_REQUIRED_STRONGLY_PREFERRED
	REQUIRED,
	REQUIRED_WEAKLY_PREFERRED,
	REQUIRED_PREFERRED,
	REQUIRED_STRONGLY_PREFERRED;
}
